version: '2.2'

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: create_certs
    command: >
      bash -c '
      bin/elasticsearch-certutil cert -out config/elastic-certificates.p12 -pass "";
      bin/elasticsearch-keystore create;
      pwd
      '
    working_dir: /usr/share/elasticsearch
    volumes: 
      - ./certificates:/usr/share/elasticsearch/config
    networks:
      - elastic        
networks:
  elastic:
    driver: bridge